name: dievas
publish_to: none
description: "Dievas design system — Flutter theme and component layer."
version: 0.0.1
homepage:
resolution: workspace

environment:
    sdk: ">=3.11.4 <4.0.0"
    flutter: ">=3.22.0"

dependencies:
    flutter:
        sdk: flutter
    equatable: ^2.0.5
    dievas_tokens:
        path: ../dievas_tokens
    meta: '>=1.17.0 <2.0.0'

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    fonts:
        - family: MaisonNeue
          fonts:
              - asset: packages/dievas/assets/fonts/maison_neue_medium.ttf
        - family: MaisonNeueExtended
          fonts:
              - asset: packages/dievas/assets/fonts/maison_neue_extended_medium.otf
