name: dievas
description: "Dievas design system. Flutter theme and component layer."
version: 0.0.4
repository: https://github.com/Serticode/dievas
homepage: https://dievas.serticode.com
resolution: workspace
issue_tracker: https://github.com/Serticode/dievas/issues
topics: [design-system, flutter, ui, theming]

environment:
    sdk: ">=3.11.4 <4.0.0"
    flutter: ">=3.22.0"

dependencies:
    flutter:
        sdk: flutter
    equatable: ^2.0.5
    dievas_tokens: ^0.0.3
    meta: ">=1.17.0 <2.0.0"

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    fonts:
        - family: MartianMono
          fonts:
              - asset: lib/assets/fonts/MartianMono-Light.ttf
                weight: 300
              - asset: lib/assets/fonts/MartianMono-Regular.ttf
                weight: 400
              - asset: lib/assets/fonts/MartianMono-Medium.ttf
                weight: 500
              - asset: lib/assets/fonts/MartianMono-SemiBold.ttf
                weight: 600
