import 'dart:io';

import 'package:dievas_tokens/dievas_tokens.dart';

/// Converts an ARGB [int] token to a CSS `rgba()` string.
///
/// Dievas tokens are stored as ARGB ints (same layout as Flutter's Color).
/// Tailwind v4 `@theme` accepts any valid CSS colour expression.
String toRgba(int argb) {
  final a = (argb >> 24) & 0xFF;
  final r = (argb >> 16) & 0xFF;
  final g = (argb >> 8) & 0xFF;
  final b = argb & 0xFF;
  final alpha = a == 0xFF ? '1' : (a / 255).toStringAsFixed(3);
  return 'rgba($r, $g, $b, $alpha)';
}

/// Converts a [double] token to a `px` CSS string.
String toPx(double value) => '${value}px';

void main() {
  final buf = StringBuffer();

  buf.writeln('/* ─────────────────────────────────────────────────────────────');
  buf.writeln(' * Dievas Landing — Tailwind CSS Input');
  buf.writeln(' * Generated by tool/generate_theme.dart from dievas_tokens.');
  buf.writeln(' * DO NOT EDIT MANUALLY.');
  buf.writeln(' * Regenerate: dart run tool/generate_theme.dart');
  buf.writeln(' *');
  buf.writeln(' * Section-specific styles live in their own files:');
  buf.writeln(' *   base.css         — shared keyframes, utilities, reveals');
  buf.writeln(' *   nav.css          — navigation');
  buf.writeln(' *   hero.css         — hero section');
  buf.writeln(' *   manifesto.css    — manifesto section');
  buf.writeln(' *   architecture.css — architecture section');
  buf.writeln(' *   components.css   — components section');
  buf.writeln(' *   footer.css       — footer');
  buf.writeln(' * ───────────────────────────────────────────────────────────── */');
  buf.writeln();

  // ── Note: Section-specific CSS partials (base.css, nav.css, hero.css,
  //    manifesto.css, architecture.css, components.css, footer.css) are loaded
  //    via <link> tags in app.dart — NOT via CSS @import — so the Tailwind CLI
  //    can process this file without resolving external imports.

  // ── @imports FIRST (CSS spec requirement) ───────────────────────────────
  // Cascadia Code via Google Fonts CDN.
  buf.writeln('@import url("https://fonts.googleapis.com/css2?family=Cascadia+Code&display=swap");');
  buf.writeln();

  buf.writeln('@import "tailwindcss";');
  buf.writeln();

  // ── Self-hosted fonts ────────────────────────────────────────────────────
  // Maison Neue is not on Google Fonts — we self-host the WOFF2.
  buf.writeln('@font-face {');
  buf.writeln('  font-family: "MaisonNeueExtended";');
  buf.writeln('  src: url("/assets/fonts/maison-neue-extended-medium.woff2") format("woff2");');
  buf.writeln('  font-weight: 500;');
  buf.writeln('  font-style: normal;');
  buf.writeln('  font-display: swap;');
  buf.writeln('}');
  buf.writeln();
  buf.writeln('@font-face {');
  buf.writeln('  font-family: "MaisonNeue";');
  buf.writeln('  src: url("/assets/fonts/maison-neue-medium.woff2") format("woff2");');
  buf.writeln('  font-weight: 500;');
  buf.writeln('  font-style: normal;');
  buf.writeln('  font-display: swap;');
  buf.writeln('}');
  buf.writeln();
  // Tell Tailwind v4 to scan Dart files for class names in addition to
  // the default sources. The path is relative to this styles.css file.
  buf.writeln('@source "../lib/**/*.dart";');
  buf.writeln();
  buf.writeln('@theme {');

  // ── Colours (dark semantic — landing has fixed dark aesthetic) ──────────
  buf.writeln('  /* ── Colours — DievasColourSemanticDark ──────────────────── */');
  buf.writeln();

  buf.writeln('  /* Brand */');
  buf.writeln('  --color-brand:        ${toRgba(DievasColourSemanticDark.brand)};');
  buf.writeln('  --color-brand-subtle: ${toRgba(DievasColourSemanticDark.brandSubtle)};');
  buf.writeln('  --color-on-brand:     ${toRgba(DievasColourSemanticDark.onBrand)};');
  buf.writeln();

  buf.writeln('  /* Text */');
  buf.writeln('  --color-text-hi:  ${toRgba(DievasColourSemanticDark.textPrimary)};');
  buf.writeln('  --color-text-mid: ${toRgba(DievasColourSemanticDark.textSecondary)};');
  buf.writeln('  --color-text-lo:  ${toRgba(DievasColourSemanticDark.textTertiary)};');
  buf.writeln('  --color-text-off: ${toRgba(DievasColourSemanticDark.textDisabled)};');
  buf.writeln();

  buf.writeln('  /* Background */');
  buf.writeln('  --color-bg-base:     ${toRgba(DievasColourSemanticDark.bgBase)};');
  buf.writeln('  --color-bg-subtle:   ${toRgba(DievasColourSemanticDark.bgSubtle)};');
  buf.writeln('  --color-bg-elevated: ${toRgba(DievasColourSemanticDark.bgElevated)};');
  buf.writeln('  --color-bg-overlay:  ${toRgba(DievasColourSemanticDark.bgOverlay)};');
  buf.writeln();

  buf.writeln('  /* Border */');
  buf.writeln('  --color-border:       ${toRgba(DievasColourSemanticDark.borderDefault)};');
  buf.writeln('  --color-border-hi:    ${toRgba(DievasColourSemanticDark.borderStrong)};');
  buf.writeln('  --color-border-brand: ${toRgba(DievasColourSemanticDark.borderBrand)};');
  buf.writeln('  --color-border-focus: ${toRgba(DievasColourSemanticDark.borderFocus)};');
  buf.writeln();

  buf.writeln('  /* Action */');
  buf.writeln('  --color-action:          ${toRgba(DievasColourSemanticDark.actionPrimary)};');
  buf.writeln('  --color-action-hover:    ${toRgba(DievasColourSemanticDark.actionPrimaryHover)};');
  buf.writeln('  --color-action-active:   ${toRgba(DievasColourSemanticDark.actionPrimaryActive)};');
  buf.writeln('  --color-action-disabled: ${toRgba(DievasColourSemanticDark.actionPrimaryDisabled)};');
  buf.writeln('  --color-action-sec:      ${toRgba(DievasColourSemanticDark.actionSecondary)};');
  buf.writeln('  --color-action-sec-hover:${toRgba(DievasColourSemanticDark.actionSecondaryHover)};');
  buf.writeln();

  buf.writeln('  /* Static */');
  buf.writeln('  --color-static-white: ${toRgba(DievasColourSemanticDark.staticWhite)};');
  buf.writeln('  --color-static-black: ${toRgba(DievasColourSemanticDark.staticBlack)};');
  buf.writeln();

  // ── Typography ─────────────────────────────────────────────────────────
  buf.writeln('  /* ── Typography ─────────────────────────────────────────────── */');
  buf.writeln('  --font-display: "MaisonNeueExtended", system-ui, sans-serif;');
  buf.writeln('  --font-body:    "MaisonNeue", system-ui, sans-serif;');
  buf.writeln('  --font-mono:    "Cascadia Code", ui-monospace, monospace;');
  buf.writeln();

  // ── Spacing ────────────────────────────────────────────────────────────
  buf.writeln('  /* ── Spacing — DievasSpacingSemantic ─────────────────────── */');
  buf.writeln('  --spacing-xs:   ${toPx(DievasSpacingSemantic.xs)};');
  buf.writeln('  --spacing-sm:   ${toPx(DievasSpacingSemantic.sm)};');
  buf.writeln('  --spacing-md:   ${toPx(DievasSpacingSemantic.md)};');
  buf.writeln('  --spacing-lg:   ${toPx(DievasSpacingSemantic.lg)};');
  buf.writeln('  --spacing-xl:   ${toPx(DievasSpacingSemantic.xl)};');
  buf.writeln('  --spacing-2xl:  ${toPx(DievasSpacingSemantic.x2l)};');
  buf.writeln('  --spacing-3xl:  ${toPx(DievasSpacingSemantic.x3l)};');
  buf.writeln('  --spacing-4xl:  ${toPx(DievasSpacingSemantic.x4l)};');
  buf.writeln('  --spacing-5xl:  ${toPx(DievasSpacingSemantic.x5l)};');
  buf.writeln();

  // ── Radius ─────────────────────────────────────────────────────────────
  buf.writeln('  /* ── Radius — DievasRadiusSemantic ───────────────────────── */');
  buf.writeln('  --radius-xs:   ${toPx(DievasRadiusSemantic.xs)};');
  buf.writeln('  --radius-sm:   ${toPx(DievasRadiusSemantic.sm)};');
  buf.writeln('  --radius-md:   ${toPx(DievasRadiusSemantic.md)};');
  buf.writeln('  --radius-lg:   ${toPx(DievasRadiusSemantic.lg)};');
  buf.writeln('  --radius-xl:   ${toPx(DievasRadiusSemantic.xl)};');
  buf.writeln('  --radius-2xl:  ${toPx(DievasRadiusSemantic.x2l)};');
  buf.writeln('  --radius-3xl:  ${toPx(DievasRadiusSemantic.x3l)};');
  buf.writeln('  --radius-full: ${toPx(DievasRadiusSemantic.full)};');
  buf.writeln();

  buf.writeln('}');
  buf.writeln();

  // ── Note: shared keyframes (fade-up, float, float-slow, eyebrow-shimmer),
  //    .section-eyebrow, and @layer utilities now live in web/base.css to keep
  //    this generated file focused on Tailwind theme tokens.

  final outputFile = File('web/styles.css');
  outputFile.writeAsStringSync(buf.toString());
  print('✓ web/styles.css generated from dievas_tokens');
  print('  Next: npm run build:css → regenerate web/output.css');
}
