// ignore_for_file: avoid_print
import 'dart:io';

import 'package:dievas_tokens/dievas_tokens.dart';

/// Converts an ARGB [int] token to a CSS `rgba()` string.
///
/// Dievas tokens are stored as ARGB ints (same layout as Flutter's Color).
/// Tailwind v4 `@theme` accepts any valid CSS colour expression.
String toRgba(int argb) {
  final a = (argb >> 24) & 0xFF;
  final r = (argb >> 16) & 0xFF;
  final g = (argb >> 8) & 0xFF;
  final b = argb & 0xFF;
  final alpha = a == 0xFF ? '1' : (a / 255).toStringAsFixed(3);
  return 'rgba($r, $g, $b, $alpha)';
}

/// Converts a [double] token to a `px` CSS string.
String toPx(double value) => '${value}px';

void main() {
  final buf = StringBuffer();

  buf.writeln('/* ─────────────────────────────────────────────────────────────');
  buf.writeln(' * Dievas Landing — Tailwind CSS Input');
  buf.writeln(' * Generated by tool/generate_theme.dart from dievas_tokens.');
  buf.writeln(' * DO NOT EDIT MANUALLY.');
  buf.writeln(' * Regenerate: dart run tool/generate_theme.dart');
  buf.writeln(' * ───────────────────────────────────────────────────────────── */');
  buf.writeln();

  // ── Self-hosted fonts ────────────────────────────────────────────────────
  buf.writeln('@font-face {');
  buf.writeln('  font-family: "Maison Neue Extended";');
  buf.writeln('  src: url("/assets/fonts/maison-neue-extended-medium.woff2") format("woff2");');
  buf.writeln('  font-weight: 500;');
  buf.writeln('  font-style: normal;');
  buf.writeln('  font-display: swap;');
  buf.writeln('}');
  buf.writeln();
  buf.writeln('@font-face {');
  buf.writeln('  font-family: "Maison Neue";');
  buf.writeln('  src: url("/assets/fonts/maison-neue-medium.woff2") format("woff2");');
  buf.writeln('  font-weight: 500;');
  buf.writeln('  font-style: normal;');
  buf.writeln('  font-display: swap;');
  buf.writeln('}');
  buf.writeln();

  buf.writeln('@import "tailwindcss";');
  buf.writeln();
  // Tell Tailwind v4 to scan Dart files for class names in addition to
  // the default sources. The path is relative to this styles.css file.
  buf.writeln('@source "../lib/**/*.dart";');
  buf.writeln();
  buf.writeln('@theme {');

  // ── Colours (dark semantic — landing has fixed dark aesthetic) ──────────
  buf.writeln('  /* ── Colours — DievasColourSemanticDark ──────────────────── */');
  buf.writeln();

  buf.writeln('  /* Brand */');
  buf.writeln('  --color-brand:        ${toRgba(DievasColourSemanticDark.brand)};');
  buf.writeln('  --color-brand-subtle: ${toRgba(DievasColourSemanticDark.brandSubtle)};');
  buf.writeln('  --color-on-brand:     ${toRgba(DievasColourSemanticDark.onBrand)};');
  buf.writeln();

  buf.writeln('  /* Text */');
  buf.writeln('  --color-text-hi:  ${toRgba(DievasColourSemanticDark.textPrimary)};');
  buf.writeln('  --color-text-mid: ${toRgba(DievasColourSemanticDark.textSecondary)};');
  buf.writeln('  --color-text-lo:  ${toRgba(DievasColourSemanticDark.textTertiary)};');
  buf.writeln('  --color-text-off: ${toRgba(DievasColourSemanticDark.textDisabled)};');
  buf.writeln();

  buf.writeln('  /* Background */');
  buf.writeln('  --color-bg-base:     ${toRgba(DievasColourSemanticDark.bgBase)};');
  buf.writeln('  --color-bg-subtle:   ${toRgba(DievasColourSemanticDark.bgSubtle)};');
  buf.writeln('  --color-bg-elevated: ${toRgba(DievasColourSemanticDark.bgElevated)};');
  buf.writeln('  --color-bg-overlay:  ${toRgba(DievasColourSemanticDark.bgOverlay)};');
  buf.writeln();

  buf.writeln('  /* Border */');
  buf.writeln('  --color-border:       ${toRgba(DievasColourSemanticDark.borderDefault)};');
  buf.writeln('  --color-border-hi:    ${toRgba(DievasColourSemanticDark.borderStrong)};');
  buf.writeln('  --color-border-brand: ${toRgba(DievasColourSemanticDark.borderBrand)};');
  buf.writeln('  --color-border-focus: ${toRgba(DievasColourSemanticDark.borderFocus)};');
  buf.writeln();

  buf.writeln('  /* Action */');
  buf.writeln('  --color-action:          ${toRgba(DievasColourSemanticDark.actionPrimary)};');
  buf.writeln('  --color-action-hover:    ${toRgba(DievasColourSemanticDark.actionPrimaryHover)};');
  buf.writeln('  --color-action-active:   ${toRgba(DievasColourSemanticDark.actionPrimaryActive)};');
  buf.writeln('  --color-action-disabled: ${toRgba(DievasColourSemanticDark.actionPrimaryDisabled)};');
  buf.writeln('  --color-action-sec:      ${toRgba(DievasColourSemanticDark.actionSecondary)};');
  buf.writeln('  --color-action-sec-hover:${toRgba(DievasColourSemanticDark.actionSecondaryHover)};');
  buf.writeln();

  buf.writeln('  /* Static */');
  buf.writeln('  --color-static-white: ${toRgba(DievasColourSemanticDark.staticWhite)};');
  buf.writeln('  --color-static-black: ${toRgba(DievasColourSemanticDark.staticBlack)};');
  buf.writeln();

  // ── Typography ─────────────────────────────────────────────────────────
  buf.writeln('  /* ── Typography ─────────────────────────────────────────────── */');
  buf.writeln('  --font-display: "Maison Neue Extended", system-ui, sans-serif;');
  buf.writeln('  --font-body:    "Maison Neue", system-ui, sans-serif;');
  buf.writeln();

  // ── Spacing ────────────────────────────────────────────────────────────
  buf.writeln('  /* ── Spacing — DievasSpacingSemantic ─────────────────────── */');
  buf.writeln('  --spacing-xs:   ${toPx(DievasSpacingSemantic.xs)};');
  buf.writeln('  --spacing-sm:   ${toPx(DievasSpacingSemantic.sm)};');
  buf.writeln('  --spacing-md:   ${toPx(DievasSpacingSemantic.md)};');
  buf.writeln('  --spacing-lg:   ${toPx(DievasSpacingSemantic.lg)};');
  buf.writeln('  --spacing-xl:   ${toPx(DievasSpacingSemantic.xl)};');
  buf.writeln('  --spacing-2xl:  ${toPx(DievasSpacingSemantic.x2l)};');
  buf.writeln('  --spacing-3xl:  ${toPx(DievasSpacingSemantic.x3l)};');
  buf.writeln('  --spacing-4xl:  ${toPx(DievasSpacingSemantic.x4l)};');
  buf.writeln('  --spacing-5xl:  ${toPx(DievasSpacingSemantic.x5l)};');
  buf.writeln();

  // ── Radius ─────────────────────────────────────────────────────────────
  buf.writeln('  /* ── Radius — DievasRadiusSemantic ───────────────────────── */');
  buf.writeln('  --radius-xs:   ${toPx(DievasRadiusSemantic.xs)};');
  buf.writeln('  --radius-sm:   ${toPx(DievasRadiusSemantic.sm)};');
  buf.writeln('  --radius-md:   ${toPx(DievasRadiusSemantic.md)};');
  buf.writeln('  --radius-lg:   ${toPx(DievasRadiusSemantic.lg)};');
  buf.writeln('  --radius-xl:   ${toPx(DievasRadiusSemantic.xl)};');
  buf.writeln('  --radius-2xl:  ${toPx(DievasRadiusSemantic.x2l)};');
  buf.writeln('  --radius-3xl:  ${toPx(DievasRadiusSemantic.x3l)};');
  buf.writeln('  --radius-full: ${toPx(DievasRadiusSemantic.full)};');
  buf.writeln();

  buf.writeln('}');
  buf.writeln();

  // ── Animations ─────────────────────────────────────────────────────────
  buf.writeln('@keyframes fade-up {');
  buf.writeln('  from { opacity: 0; transform: translateY(16px); }');
  buf.writeln('  to   { opacity: 1; transform: translateY(0); }');
  buf.writeln('}');
  buf.writeln();
  buf.writeln('@keyframes float {');
  buf.writeln('  0%, 100% { transform: translateY(0px); }');
  buf.writeln('  50%       { transform: translateY(-12px); }');
  buf.writeln('}');
  buf.writeln();
  buf.writeln('@keyframes float-slow {');
  buf.writeln('  0%, 100% { transform: translateY(0px); }');
  buf.writeln('  50%       { transform: translateY(-8px); }');
  buf.writeln('}');
  buf.writeln();

  // ── Eyebrow shimmer ────────────────────────────────────────────────────
  buf.writeln('@keyframes eyebrow-shimmer {');
  buf.writeln('  0%   { background-position:  200% center; }');
  buf.writeln('  100% { background-position: -200% center; }');
  buf.writeln('}');
  buf.writeln();
  buf.writeln('.section-eyebrow {');
  buf.writeln('  background: linear-gradient(');
  buf.writeln('    90deg,');
  buf.writeln('    rgba(100,116,139,1) 0%,');
  buf.writeln('    rgba(100,116,139,1) 25%,');
  buf.writeln('    rgba(129,140,248,1) 50%,');
  buf.writeln('    rgba(100,116,139,1) 75%,');
  buf.writeln('    rgba(100,116,139,1) 100%');
  buf.writeln('  );');
  buf.writeln('  background-size: 200% auto;');
  buf.writeln('  -webkit-background-clip: text;');
  buf.writeln('  -webkit-text-fill-color: transparent;');
  buf.writeln('  background-clip: text;');
  buf.writeln('  color: transparent;');
  buf.writeln('  animation: eyebrow-shimmer 5s linear infinite;');
  buf.writeln('}');
  buf.writeln();

  // ── Named max-width overrides (Tailwind v4 does not ship these by default)
  buf.writeln('@layer utilities {');
  buf.writeln('  .max-w-5xl { max-width: 64rem; }');
  buf.writeln('  .max-w-lg  { max-width: 32rem; }');
  buf.writeln('  .max-w-sm  { max-width: 24rem; }');
  buf.writeln('}');

  final outputFile = File('web/styles.css');
  outputFile.writeAsStringSync(buf.toString());
  print('✓ web/styles.css generated from dievas_tokens');
  print('  Next: npm run build:css → regenerate web/output.css');
}
